# Generated by Django 4.2 on 2023-04-26 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_userportfolio_friends'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.BigIntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.CreateModel(
            name='FavoritePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в избранное')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='blog.post', verbose_name='Понравившийся пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='portfolio.userportfolio', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Понравившийся пост',
                'verbose_name_plural': 'Понравившийся посты',
                'ordering': ['-created'],
            },
        ),
    ]
