# Generated by Django 4.2 on 2023-04-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userportfolio_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
