# Generated by Django 4.2 on 2023-04-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_likes_favoritepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='FavoritePost',
        ),
    ]
