# Generated by Django 4.2 on 2023-04-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_raiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='raiting',
            field=models.BigIntegerField(default=0, help_text='Это поле обнавляется раз в промежуток времени', verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='post',
            name='raiting',
            field=models.BigIntegerField(default=0, help_text='Это поле обнавляется раз в промежуток времени', verbose_name='Рейтинг'),
        ),
    ]
