# Generated by Django 4.2 on 2023-04-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_userportfolio_friends'),
        ('like_dislike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.userportfolio', verbose_name='Пользователь'),
        ),
    ]
